import { NextResponse } from "next/server";

// Demo emails simulating what an accounting firm inbox looks like
const demoEmails = [
  {
    id: "em_001",
    from: "svanda@montservis.cz",
    fromName: "Martin Svanda",
    to: "mail@schekonom.cz",
    subject: "Faktury za brezen 2026 - MontServis",
    preview:
      "Dobry den, posilam faktury za brezen. V priloze naleznete 3 prijate faktury od dodavatelu a jednu vydanou za servisni prace.",
    body: "Dobry den,\n\nposilam faktury za brezen 2026. V priloze naleznete:\n- Faktura c. 2026-0341 od REKO s.r.o. (material)\n- Faktura c. 2026-0342 od AutoPlyn Cheb (PHM)\n- Faktura c. 2026-0343 od Vodafone (telefony)\n- Vydana faktura c. FV-2026-089 za servisni prace pro Stav-Mont a.s.\n\nDekuji a preji hezky den,\nMartin Svanda\nMontServis s.r.o.",
    date: "2026-04-11T14:23:00",
    read: false,
    hasAttachments: true,
    attachmentCount: 4,
    companyId: "comp_montservis",
    sentiment: "neutral" as const,
    category: "documents" as const,
  },
  {
    id: "em_002",
    from: "podatelna@fs.mfcr.cz",
    fromName: "Financni urad pro Karlovarsky kraj",
    to: "mail@schekonom.cz",
    subject: "Vyzva k odstraneni pochybnosti - DPH 03/2026",
    preview:
      "Financni urad pro Karlovarsky kraj, uzemni pracoviste v Chebu, Vas vyzva k odstraneni pochybnosti v podanem Priznani k DPH...",
    body: "Financni urad pro Karlovarsky kraj\nUzemni pracoviste v Chebu\n\nVec: Vyzva k odstraneni pochybnosti\n\nFinancni urad Vas vyzva k odstraneni pochybnosti v podanem Priznani k dani z pridane hodnoty za zdanovaci obdobi brezen 2026, podanem dne 21.03.2026.\n\nPochybnost se tyka radku 40 - Odpocet dane, kde je uplatnena castka 245 000 CZK bez dostatecne prukazu.\n\nLhuta pro odpoved: 15 dnu od doruceni.\n\nS pozdravem\nIng. Jana Kralova\nSpravce dane",
    date: "2026-04-11T10:05:00",
    read: false,
    hasAttachments: true,
    attachmentCount: 1,
    companyId: "comp_montservis",
    sentiment: "negative" as const,
    category: "tax" as const,
  },
  {
    id: "em_003",
    from: "schmidt@bauteam-nord.de",
    fromName: "Klaus Schmidt",
    to: "otto.zeitler@schekonom.cz",
    subject: "Freistellungsbescheinigung - Verlangerung 2026",
    preview:
      "Sehr geehrter Herr Zeitler, ich bitte Sie um die Verlangerung unserer Freistellungsbescheinigung fur das Jahr 2026...",
    body: "Sehr geehrter Herr Zeitler,\n\nich bitte Sie um die Verlangerung unserer Freistellungsbescheinigung fur das Jahr 2026. Die aktuelle Bescheinigung lauft am 30.04.2026 aus.\n\nBitte teilen Sie mir mit, welche Unterlagen Sie benotigen.\n\nMit freundlichen Grussen,\nKlaus Schmidt\nBauTeam Nord GmbH",
    date: "2026-04-11T08:30:00",
    read: true,
    hasAttachments: false,
    attachmentCount: 0,
    companyId: "comp_bauteam",
    sentiment: "neutral" as const,
    category: "tax" as const,
  },
  {
    id: "em_004",
    from: "poupova@schekonom.cz",
    fromName: "Petra Poupova",
    to: "all@schekonom.cz",
    subject: "Porada team - streda 16.4. v 9:00",
    preview:
      "Kolegove, pripominam pravidelnou poradu v stredu. Prosim o pripravu statusu klientu a prehled nesplnenych ukolu.",
    body: "Kolegove,\n\npripominam pravidelnou teamovou poradu v stredu 16.4. v 9:00.\n\nProgram:\n1. Status klientu - kazdy referuje sve klienty\n2. Nesplnene ukoly a terminy\n3. Novinka - integrace AI asistenta\n4. Ruzne\n\nProsim o docasnost.\n\nPetra Poupova\nSCH-EKONOM s.r.o.",
    date: "2026-04-10T16:45:00",
    read: true,
    hasAttachments: false,
    attachmentCount: 0,
    companyId: "",
    sentiment: "neutral" as const,
    category: "internal" as const,
  },
  {
    id: "em_005",
    from: "novak@pendleri-novak.cz",
    fromName: "Jaroslav Novak",
    to: "mail@schekonom.cz",
    subject: "Kdy bude hotove danove priznani za 2025?",
    preview:
      "Dobry den, chtel bych se zeptat, kdy bude moje danove priznani za rok 2025 hotove? Kolega rikal, ze uz mel zpet penize...",
    body: "Dobry den,\n\nchtel bych se zeptat, kdy bude moje danove priznani za rok 2025 hotove? Kolega mi rikal, ze uz dostal zpet penize z Nemecka.\n\nMoje Lohnsteuerbescheinigung jsem Vam posilal v unoru. Je to ok, nebo potrebujete jeste neco?\n\nDekuji za info.\nJaroslav Novak",
    date: "2026-04-10T13:12:00",
    read: false,
    hasAttachments: false,
    attachmentCount: 0,
    companyId: "comp_pendler",
    sentiment: "negative" as const,
    category: "tax" as const,
  },
  {
    id: "em_006",
    from: "mzdova@schekonom.cz",
    fromName: "Lenka Horakova",
    to: "svanda@montservis.cz",
    subject: "Mzdove podklady 04/2026 - prosba o doplneni",
    preview:
      "Dobry den, pro zpracovani mezd za duben 2026 potrebuji od Vas doplnit: dochazkovy list noveho zamestnance Petra Kucery...",
    body: "Dobry den, pane Svando,\n\npro zpracovani mezd za duben 2026 potrebuji od Vas doplnit:\n\n1. Dochazkovy list noveho zamestnance Petra Kucery\n2. Potvrzeni o skonceni pracovni neschopnosti p. Marka Horanika (nastup 7.4.)\n3. Info o prescasech za brezen - nekteri zamestnanci nejsou v evidenci\n\nTermin pro doruceni: do 18.4.2026\n\nDekuji,\nLenka Horakova\nMzdova uctarka, SCH-EKONOM s.r.o.",
    date: "2026-04-10T10:30:00",
    read: true,
    hasAttachments: true,
    attachmentCount: 1,
    companyId: "comp_montservis",
    sentiment: "neutral" as const,
    category: "payroll" as const,
  },
  {
    id: "em_007",
    from: "certifikace@ica.cz",
    fromName: "I.CA - Prvni certifikacni autorita",
    to: "mail@schekonom.cz",
    subject: "Upozorneni: Kvalifikovany certifikat expiruje za 30 dni",
    preview:
      "Vazeny klient, Vas kvalifikovany certifikat c. 2024-QC-88412 expiruje dne 12.05.2026. Pro obnovu navstivte nase pobocky...",
    body: "Vazeny kliente,\n\nVas kvalifikovany certifikat c. 2024-QC-88412 vydany pro subjekt SCH-EKONOM s.r.o. expiruje dne 12.05.2026.\n\nPro obnovu certifikatu:\n1. Navstivte nasi pobocku s platnym OP\n2. Nebo vyuzijte online obnovu pres klientsky portal\n\nBez platneho certifikatu nebude mozne podepisovat danove pisemnosti.\n\nI.CA - Prvni certifikacni autorita, a.s.",
    date: "2026-04-09T08:00:00",
    read: true,
    hasAttachments: false,
    attachmentCount: 0,
    companyId: "",
    sentiment: "negative" as const,
    category: "compliance" as const,
  },
  {
    id: "em_008",
    from: "fakturace@vodafone.cz",
    fromName: "Vodafone CZ",
    to: "mail@schekonom.cz",
    subject: "Vase faktura c. VF-2026-04-SCH je pripravena",
    preview:
      "Dobry den, Vase mesicni faktura za sluzby Vodafone je pripravena ke stazeni. Castka: 2 890 CZK vcetne DPH.",
    body: "Dobry den,\n\nVase mesicni faktura za sluzby Vodafone je pripravena:\n\nCislo faktury: VF-2026-04-SCH\nCastka: 2 890 CZK vcetne DPH\nDatum splatnosti: 28.04.2026\n\nFakturu naleznete v priloze nebo ve svem klientskem portalu.\n\nVodafone Czech Republic a.s.",
    date: "2026-04-08T06:00:00",
    read: true,
    hasAttachments: true,
    attachmentCount: 1,
    companyId: "",
    sentiment: "neutral" as const,
    category: "documents" as const,
  },
  {
    id: "em_009",
    from: "info@finanzamt-weiden.de",
    fromName: "Finanzamt Weiden i.d.OPf.",
    to: "otto.zeitler@schekonom.cz",
    subject: "Steuerbescheid 2025 - BauTeam Nord GmbH",
    preview:
      "Sehr geehrte Damen und Herren, im Anhang ubersenden wir Ihnen den Steuerbescheid fur das Veranlagungsjahr 2025...",
    body: "Sehr geehrte Damen und Herren,\n\nim Anhang ubersenden wir Ihnen den Steuerbescheid fur das Veranlagungsjahr 2025.\n\nBitte prufen Sie den Bescheid und legen Sie innerhalb von 4 Wochen Einspruch ein, falls Sie Einwande haben.\n\nSteuernummer: 201/123/45678\nFestsetzung: 12.450,00 EUR\n\nMit freundlichen Grussen,\nFinanzamt Weiden i.d.OPf.",
    date: "2026-04-08T09:15:00",
    read: false,
    hasAttachments: true,
    attachmentCount: 2,
    companyId: "comp_bauteam",
    sentiment: "neutral" as const,
    category: "tax" as const,
  },
  {
    id: "em_010",
    from: "havel@elektro-havel.cz",
    fromName: "Tomas Havel",
    to: "mail@schekonom.cz",
    subject: "Zmena bankovniho uctu - prosba o aktualizaci",
    preview:
      "Dobry den, oznamuji Vam zmenu bankovniho uctu nasi firmy. Novy ucet: 2700123456/2010 (Fio banka). Stary ucet u CSOB rusime...",
    body: "Dobry den,\n\noznamuji Vam zmenu bankovniho uctu nasi firmy Elektro-Havel s.r.o.\n\nNovy ucet: 2700123456/2010 (Fio banka)\nStary ucet: 196543210/0300 (CSOB) - bude zrusen k 30.4.2026\n\nProsim o aktualizaci v ucetnictvi a take v registraci k DPH.\n\nDekuji,\nTomas Havel\nElektro-Havel s.r.o.",
    date: "2026-04-07T15:40:00",
    read: true,
    hasAttachments: false,
    attachmentCount: 0,
    companyId: "comp_elektro",
    sentiment: "neutral" as const,
    category: "documents" as const,
  },
  {
    id: "em_011",
    from: "newsletter@pohoda.cz",
    fromName: "Stormware POHODA",
    to: "mail@schekonom.cz",
    subject: "Aktualizace POHODA 2026 Release 2 - co je noveho",
    preview:
      "Vazeni uzivatele, s radosti Vam oznamujeme vydani aktualizace POHODA 2026 Release 2 s podporou noveho formatu kontrolniho hlaseni...",
    body: "Vazeni uzivatele,\n\nvydali jsme aktualizaci POHODA 2026 Release 2.\n\nNovinky:\n- Novy format kontrolniho hlaseni DPH\n- Podpora datovych schranek 2.0\n- Vylepseny import bankovnich vypisu\n- Oprava chyb v modulu Mzdy\n\nAktualizaci provedete v menu Napoveda > Aktualizace.\n\nTeam Stormware",
    date: "2026-04-07T08:00:00",
    read: true,
    hasAttachments: false,
    attachmentCount: 0,
    companyId: "",
    sentiment: "neutral" as const,
    category: "spam" as const,
  },
  {
    id: "em_012",
    from: "cssz-podatelna@cssz.cz",
    fromName: "CSSZ - Ceska sprava socialniho zabezpeceni",
    to: "mail@schekonom.cz",
    subject: "Potvrzeni prijeti Prehledu o prijmech za 03/2026",
    preview:
      "Potvrzujeme prijeti Prehledu o vysi pojistneho za mesic 03/2026 pro subjekt MontServis s.r.o., IC 12345678.",
    body: "Ceska sprava socialniho zabezpeceni\n\nPotvrzeni prijeti podani\n\nPotvrzujeme prijeti elektronickeho podani:\nTyp: Prehled o vysi pojistneho\nObdobi: 03/2026\nSubjekt: MontServis s.r.o.\nIC: 12345678\nDatum prijeti: 10.04.2026 v 09:12\nCislo podani: CSSZ-2026-04-88541\n\nDokument byl uspesne zpracovan.\n\nCSSZ",
    date: "2026-04-10T09:12:00",
    read: true,
    hasAttachments: true,
    attachmentCount: 1,
    companyId: "comp_montservis",
    sentiment: "positive" as const,
    category: "compliance" as const,
  },
  {
    id: "em_013",
    from: "muller@pendler-beratung.de",
    fromName: "Hans Muller",
    to: "mail@schekonom.cz",
    subject: "Kindergeld Antrag - chybejici doklad",
    preview:
      "Guten Tag, fur den Kindergeldantrag Ihres Mandanten J. Novak benotigen wir noch die Geburtsurkunde des zweiten Kindes...",
    body: "Guten Tag,\n\nfur den Kindergeldantrag Ihres Mandanten Jaroslav Novak (StNr: 201/456/78912) benotigen wir noch:\n\n1. Geburtsurkunde des zweiten Kindes (Anna Novakova, geb. 2024)\n2. Schulbescheinigung des ersten Kindes (Jan Novak)\n3. Meldebestätigung - aktuell\n\nBitte senden Sie die Unterlagen bis zum 20.04.2026.\n\nMit freundlichen Grussen,\nHans Muller\nFamilienkasse Bayern Nord",
    date: "2026-04-09T11:20:00",
    read: false,
    hasAttachments: false,
    attachmentCount: 0,
    companyId: "comp_pendler",
    sentiment: "neutral" as const,
    category: "tax" as const,
  },
  {
    id: "em_014",
    from: "webinar@komora-ucetnich.cz",
    fromName: "Komora danovych poradcu",
    to: "poupova@schekonom.cz",
    subject: "Pozvanka: Novela zakona o DPH 2026 - online seminar",
    preview:
      "Vazena pani Poupova, zveme Vas na online seminar k novele zakona o DPH platne od 1.7.2026. Termin: 22.4.2026, 14:00-16:00.",
    body: "Vazena pani Poupova,\n\nzveme Vas na online seminar:\n\nTema: Novela zakona o DPH platna od 1.7.2026\nTermin: 22.4.2026, 14:00-16:00\nLektor: JUDr. Martin Kopecky\n\nBody KDP: 2 body\n\nRegistrace: https://komora-ucetnich.cz/webinar/dph-2026\n\nS pozdravem,\nKomora danovych poradcu CR",
    date: "2026-04-08T12:00:00",
    read: true,
    hasAttachments: false,
    attachmentCount: 0,
    companyId: "",
    sentiment: "positive" as const,
    category: "internal" as const,
  },
  {
    id: "em_015",
    from: "accounting-ai@schekonom.cz",
    fromName: "SCH-EKONOM AI System",
    to: "poupova@schekonom.cz",
    subject: "Automaticke sparovani: 12 transakci uspesne prirazeno",
    preview:
      "Denni report: AI system automaticky sparoval 12 z 15 bankovnich transakci. 3 transakce vyzaduji manualni kontrolu.",
    body: "SCH-EKONOM AI System - Denni report\n\nDatum: 11.04.2026\n\nAutomaticke sparovani bankovnich transakci:\n- Celkem transakci: 15\n- Automaticky sparovano: 12 (80%)\n- Vyzaduje manualni kontrolu: 3\n\nNesparovane transakce:\n1. MontServis - 18 450 CZK (chybi faktura)\n2. Elektro-Havel - 5 200 EUR (neznamy VS)\n3. Pendleri-Novak - 1 200 CZK (duplicitni platba?)\n\nKliknutim zobrazite detail v portalu.",
    date: "2026-04-11T22:00:00",
    read: false,
    hasAttachments: false,
    attachmentCount: 0,
    companyId: "",
    sentiment: "positive" as const,
    category: "system" as const,
  },
];

export async function GET() {
  // In production, this would connect to IMAP
  // const imap = process.env.IMAP_HOST ? await connectImap() : null;
  return NextResponse.json({
    emails: demoEmails,
    total: demoEmails.length,
    unread: demoEmails.filter((e) => !e.read).length,
  });
}
